# NOTE:
#  I had to modify the /etc/ansible/ansible.cfg file in order to have this code working
#  I added -o ForwardAgent=yes to the ssh_args setting
#  
# Troubleshooting:
#   When the synchronization hangs:
#     - Deb 2 needs Deb1 ssh public key (ssh-copy-id -i ~/.ssh/id_rsa cesar@192.168.56.102)
#     - remote_user=root does not need to be UNcommented in /etc/ansible/ansible.cfn

---
- hosts: debian1
  vars :
    filename: file_from_debian1.txt
  tasks:
    - name: Create a file to be copy to debian2 later on 
      file:
        path: /tmp/{{ filename }}
        state: touch

- hosts: debian2
  vars :
    filename: file_from_debian1.txt
  tasks:
    - name: Move file from debian1 to debian 2
      synchronize:
        src: /tmp/{{ filename }}
        dest: /tmp
      delegate_to: "{{ groups.debian1[0] }}"