#
# Playbook to delete employees DB from dbservers group
#

---
- hosts: dbservers
  become: true
  vars:
    dump_file_name: dump_employees
    info_host: "{{ ansible_fqdn }}"
  tasks:
    - name: Delete employees database
      mysql_db:
        name: employees
        state: absent
    - name: Delete dump in /tmp
      file: 
        path: /tmp/{{ dump_file_name }}_{{ info_host }}.sql
        state: absent
    - name: Delete test_db folder
      file: 
        path: /tmp/test_db
        state: absent

